#pragma once

float QuadIn(float time, float totalTime, float start, float end);
float QuadOut(float time, float totalTime, float start, float end);
float QuadInOut(float time, float totaltime, float start, float end);
float CubicIn(float time, float totaltime, float start, float end);
float CubicOut(float time, float totaltime, float start, float end);
float CubicInOut(float time, float totaltime, float start, float end);
float QuartIn(float timet, float totaltime, float start, float end);
float QuartOut(float time, float totaltime, float start, float end);
float QuartInOut(float time, float totaltime, float start, float end);
float QuintIn(float time, float totaltime, float start, float end);
float QuintOut(float time, float totaltime, float start, float end);
float QuintInOut(float time, float totaltime, float start, float end);
float SineIn(float time, float totaltime, float start, float end);
float SineOut(float time, float totaltime, float start, float end);
float SineInOut(float time, float totaltime, float start, float end);
float ExpIn(float time, float totaltime, float start, float end);
float ExpOut(float time, float totaltime, float start, float end);
float ExpInOut(float time, float totaltime, float start, float end);
float CircIn(float time, float totaltime, float start, float end);
float CircOut(float time, float totaltime, float start, float end);
float CircInOut(float time, float totaltime, float start, float end);
float ElasticIn(float time, float totaltime, float start, float end);
float ElasticOut(float time, float totaltime, float start, float end);
float ElasticInOut(float time, float totaltime, float start, float end);
float BackIn(float time, float totaltime, float start, float end, float s);
float BackOut(float time, float totaltime, float start, float end, float s);
float BackInOut(float time, float totaltime, float start, float end, float s);
float BounceIn(float time, float totaltime, float start, float end);
float BounceOut(float time, float totaltime, float start, float end);
float BounceInOut(float time, float totaltime, float start, float end);
float Linear(float time, float totaltime, float start, float end);
